# Onnuri Accounting System Configuration
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: onnuri-accounting
  
  # Profile Configuration
  profiles:
    active: dev
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/onnuri
    username: ${DB_USERNAME:onnuri}
    password: ${DB_PASSWORD:onnuri123}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      pool-name: OnnuriAccountingHikariCP
  
  # JPA & Hibernate Configuration
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop  # 테이블 자동 생성/수정
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: false
        id:
          new_generator_mappings: true
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
  
  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB
  
  
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: NON_NULL
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
  

# Logging Configuration
logging:
  level:
    com.side.onnuri: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/onnuri-accounting.log
    max-size: 100MB
    max-history: 30

# Management & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# Application Custom Properties
onnuri:
  accounting:
    file:
      upload-dir: ${FILE_UPLOAD_DIR:./uploads}
      temp-dir: ${FILE_TEMP_DIR:./temp}
      max-size: 10485760  # 10MB
    
    
    security:
      cors:
        allowed-origins:
          - http://localhost:3000
          - http://localhost:8080
          - http://localhost:5173  # Vite dev server
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowed-headers: "*"
        allow-credentials: true